import type { Metadata } from 'next';
import {SessionProvider} from './components/AuthProvider'
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.scss';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Rafael Photography Portfolio',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<SessionProvider>
				<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
					{children}
				</body>
			</SessionProvider>
		</html>
	);
}
