import type { Metadata } from 'next';
import { SessionProvider } from './components/AuthProvider';
import { Poppins } from 'next/font/google';
import './globals.scss';
import Footer from './components/Footer';
import Header from './components/Header';
import { Toaster } from 'react-hot-toast';
import MobileMenuUpdated from './components/MobileMenuUpdated';

const poppins = Poppins({
	subsets: ['latin'],
	weight: ['300', '400', '500', '600', '700'], // choose weights you need
	variable: '--font-poppins', // optional, if using CSS variable
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Rafael Photography Portfolio',
	description: 'Generated by create next app',
	icons: {
		icon: '/camera-favicon.svg',
		shortcut: '/camera-favicon.svg',
		apple: '/camera-favicon.svg',
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={poppins.className}>
			<SessionProvider>
				<body>
					<div>
						<Toaster />
					</div>
					<MobileMenuUpdated/>
					<Header />
					{children}
					<Footer />
				</body>
			</SessionProvider>
		</html>
	);
}
