import type { Metadata } from 'next';
import { SessionProvider } from './components/AuthProvider';
import { Poppins } from 'next/font/google';
import './globals.scss';

const poppins = Poppins({
	subsets: ['latin'],
	weight: ['300', '400', '500', '600', '700'], // choose weights you need
	variable: '--font-poppins', // optional, if using CSS variable
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Rafael Photography Portfolio',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={poppins.className}>
			<SessionProvider>
				<body >{children}</body>
			</SessionProvider>
		</html>
	);
}
